services:
  nginx:
    build: 
      context: .
    ports:
      - 2000:80
    volumes:
      - ./html/:/usr/share/nginx/html
      - ./images/:/usr/share/nginx/images
      - ./nginx/conf.d/:/etc/nginx/conf.d